# Correction Configuration

rollback:
  # Maximum number of versions to keep in history
  max_history: 5
  # Directory to store backup configurations
  backup_dir: "backups/"
  # Time to wait before applying changes (seconds)
  wait_time: 30

validation:
  # Package integrity checks
  integrity_check:
    enabled: true
    methods:
      - checksum
      - signature
      - source_verification
  
  # Dependency validation settings
  dependency_check:
    enabled: true
    scan_depth: 2  # Levels of dependencies to check
    verify_sources: true
    allowed_sources:
      - "pypi.org"
      - "github.com"
      - "gitlab.com"

fixing:
  # Automated fixing strategies
  strategies:
    - rollback_to_last_known_good
    - install_verified_version
    - rebuild_from_source
  
  # Safe mode installation settings
  safe_mode:
    enabled: true
    sandbox_enabled: true
    timeout: 300  # seconds
    max_retries: 3

notifications:
  # Notification settings for correction actions
  enabled: true
  methods:
    - email
    - log
  urgency_levels:
    - critical
    - warning
    - info 